#!/bin/bash
mkdir -p /var/www/html/publiccache /var/www/html/publiclogs
touch /var/www/html/public/prod.log
touch /var/www/html/public/dev.log
chgrp -R www-data .
chmod -R g+w usr/local/bin/app/cache /var/www/html/public
source /etc/apache2/envvars
tail -F /var/log/apache2/* /var/www/html/public/prod.log /var/www/html/public/dev.log &
exec apache2 -D FOREGROUND