application:
  name: ${APP_NAME}
  project: ${APP_NAME}
  publicly_accessible: true
databases:
  - type: postgresql
    version: 12
    name: my-db
routers:
  - name: main
    routes:
      - application_name: ${APP_NAME}
        paths:
          - /
