application:
  name: ${APP_NAME}
  project: ${APP_NAME}
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
  - name: main
    routes:
      - application_name: ${APP_NAME}
        paths:
          - /