application:
    name: ${APP_NAME}
    project: ${APP_NAME}
    cloud_region: aws/us-east-2
    publicly_accessible: true
  routers:
    - name: main
      routes:
        - application_name: ${APP_NAME}
          paths:
            - /
