application:
  name: ${APP_NAME}
  project: ${APP_NAME}
  cloud_region: aws/eu-west-3
  publicly_accessible: true
databases:
- type: postgresql
  version: "11.5"
  name: my-postgresql
routers:
- name: main
  custom_domains:
  - branch: master
    domain: node.algo.green
  routes:
  - application_name: ${APP_NAME}
    paths:
    - /