application:
  name: ${APP_NAME}
  project: ${PROJECT_NAME}
  publicly_accessible: true
databases:
- type: postgresql
  version: 12
  name: my-postgresql
routers:
- name: main
  routes:
  - application_name: ${APP_NAME}
    paths:
    - /*
