application:
  name: ${APP_NAME}
  project: ${PROJECT_NAME}
  cloud_region: aws/us-east-2
  publicly_accessible: true
databases:
  - type: postgresql
    version: "11"
    name: my-db
routers:
  - name: main
    routes:
      - application_name: ${APP_NAME}
        paths:
          - /
