application:
  name: ${APP_NAME}
  project: ${PROJECT_NAME}
  cloud_region: aws/eu-west-3
  publicly_accessible: true
databases:
- type: postgresql
  version: 11
  name: my-postgresql-database
routers:
- name: main
  routes:
  - application_name: ${APP_NAME}
    paths:
    - /*
